/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latiendita1;
import java.text.DecimalFormat;
import java.util.*;
import java.util.Scanner;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raul
 */
public class Tiendita extends javax.swing.JFrame {
    Scanner entrada = new Scanner(System.in);
    private static RegistroProductos rp;
    private static Productos p;
    DefaultTableModel modeloListaCol;
    DefaultTableModel modeloEfectivo;
    DefaultTableModel modeloCredito;
    DefaultTableModel modeloCheque;
    
    //Se agrega modelo de tabla para cuenta corriente
    DefaultTableModel modeloCuentaCorriente;
    //Se agregan campos para tabla modelo de cuenta corriente
    
    
    private static String fcreacionFactura;
    private static String fajusteFactura;
    private static double debe; 
    private static double haber;
    private static double saldo; 
    
    
    
    
    private static double total;
    private static String NIT;
    private static String Name;
    private static double Amount;
    private static String Tarjeta;
    private static String Cheque;
    private static CuentaEfectivo ce;
    private static RegistroEfectivo re = new RegistroEfectivo();
    private static RegistroCCredito rc = new RegistroCCredito();
    private static RegistroCheques rch = new RegistroCheques();
    private static CuentaCredito cc;
    private static CuentaCredito c;
    private static CuentaCheque cch;
    private static double subEfectivo;
    private static double subCredito;
    private static double subCheque;
    private static double TotalListados;
    
    public JTabbedPane getjTabbedPanePrincipal() {
        return jTabbedPanePrincipal;
    }

    
    
    /**
     * Creates new form Tiendita
     */
    public Tiendita() {
        initComponents();
        deshabilitarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupApple = new javax.swing.ButtonGroup();
        buttonGroupLemon = new javax.swing.ButtonGroup();
        buttonGroupTomato = new javax.swing.ButtonGroup();
        buttonGroupTipoPago = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        jPanelCaja = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jRMediaLibraApple = new javax.swing.JRadioButton();
        jRUnaLibraApple = new javax.swing.JRadioButton();
        jRLibraYMediaApple = new javax.swing.JRadioButton();
        btnApple = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jRMediaLibraLemon = new javax.swing.JRadioButton();
        jRUnaLibraLemon = new javax.swing.JRadioButton();
        jRLibraYMediaLemon = new javax.swing.JRadioButton();
        btnLemon = new javax.swing.JButton();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        btnPineapple = new javax.swing.JButton();
        jDesktopPane9 = new javax.swing.JDesktopPane();
        btnCabbage = new javax.swing.JButton();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jRMediaLibraTomato = new javax.swing.JRadioButton();
        jRUnaLibraTomato = new javax.swing.JRadioButton();
        jRLibraYMediaTomato = new javax.swing.JRadioButton();
        btnTomato = new javax.swing.JButton();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        btnWatermelon = new javax.swing.JButton();
        btnNuevaTransaccion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        txtTotalPagar = new javax.swing.JTextField();
        btnTotalPagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNoTarjeta = new javax.swing.JTextField();
        jREfectivo = new javax.swing.JRadioButton();
        jRTarjeta = new javax.swing.JRadioButton();
        jRCheque = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNoCheque = new javax.swing.JTextField();
        btnRealizarPago = new javax.swing.JButton();
        btnSalirVentas = new javax.swing.JButton();
        jPanelConsultar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaEfectivo = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaTarjeta = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaCheque = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSubEfectivo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSubCredito = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSubCheque = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTotalCorteCaja = new javax.swing.JTextField();
        btnCorteCaja = new javax.swing.JButton();
        btnSalirCorteCaja = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaCorriente = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPanePrincipal.setMaximumSize(new java.awt.Dimension(1500, 1500));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        buttonGroupApple.add(jRMediaLibraApple);
        jRMediaLibraApple.setForeground(new java.awt.Color(255, 255, 255));
        jRMediaLibraApple.setText("1/2 Libra");

        buttonGroupApple.add(jRUnaLibraApple);
        jRUnaLibraApple.setForeground(new java.awt.Color(255, 255, 255));
        jRUnaLibraApple.setText("1 Libra");

        buttonGroupApple.add(jRLibraYMediaApple);
        jRLibraYMediaApple.setForeground(new java.awt.Color(255, 255, 255));
        jRLibraYMediaApple.setText("1 1/2 Libra");

        btnApple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fruit_apple_food_1815.png"))); // NOI18N
        btnApple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppleActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jRMediaLibraApple, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRUnaLibraApple, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jRLibraYMediaApple, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnApple, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRMediaLibraApple)
                    .addComponent(jRUnaLibraApple)
                    .addComponent(jRLibraYMediaApple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnApple, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jRMediaLibraApple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRUnaLibraApple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRLibraYMediaApple)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jDesktopPane2.setBackground(new java.awt.Color(204, 204, 204));

        buttonGroupLemon.add(jRMediaLibraLemon);
        jRMediaLibraLemon.setForeground(new java.awt.Color(255, 255, 255));
        jRMediaLibraLemon.setText("1/2 Libra");

        buttonGroupLemon.add(jRUnaLibraLemon);
        jRUnaLibraLemon.setForeground(new java.awt.Color(255, 255, 255));
        jRUnaLibraLemon.setText("1 Libra");

        buttonGroupLemon.add(jRLibraYMediaLemon);
        jRLibraYMediaLemon.setForeground(new java.awt.Color(255, 255, 255));
        jRLibraYMediaLemon.setText("1 1/2 Libra");

        btnLemon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fruitfoodlemon_fruta_comida_1811.png"))); // NOI18N
        btnLemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLemonActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jRMediaLibraLemon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jRUnaLibraLemon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jRLibraYMediaLemon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnLemon, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRMediaLibraLemon)
                    .addComponent(jRUnaLibraLemon)
                    .addComponent(jRLibraYMediaLemon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLemon, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLemon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jRMediaLibraLemon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRUnaLibraLemon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRLibraYMediaLemon)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jDesktopPane7.setBackground(new java.awt.Color(204, 204, 204));

        btnPineapple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pineapple_icon-icons.com_68707.png"))); // NOI18N
        btnPineapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPineappleActionPerformed(evt);
            }
        });

        jDesktopPane7.setLayer(btnPineapple, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane7Layout = new javax.swing.GroupLayout(jDesktopPane7);
        jDesktopPane7.setLayout(jDesktopPane7Layout);
        jDesktopPane7Layout.setHorizontalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane7Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnPineapple, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane7Layout.setVerticalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPineapple, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jDesktopPane9.setBackground(new java.awt.Color(204, 204, 204));

        btnCabbage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vegetables_cabbage_food_1808.png"))); // NOI18N
        btnCabbage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabbageActionPerformed(evt);
            }
        });

        jDesktopPane9.setLayer(btnCabbage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane9Layout = new javax.swing.GroupLayout(jDesktopPane9);
        jDesktopPane9.setLayout(jDesktopPane9Layout);
        jDesktopPane9Layout.setHorizontalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnCabbage, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane9Layout.setVerticalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCabbage, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jDesktopPane4.setBackground(new java.awt.Color(204, 204, 204));

        buttonGroupTomato.add(jRMediaLibraTomato);
        jRMediaLibraTomato.setForeground(new java.awt.Color(255, 255, 255));
        jRMediaLibraTomato.setText("1/2 Libra");

        buttonGroupTomato.add(jRUnaLibraTomato);
        jRUnaLibraTomato.setForeground(new java.awt.Color(255, 255, 255));
        jRUnaLibraTomato.setText("1 Libra");

        buttonGroupTomato.add(jRLibraYMediaTomato);
        jRLibraYMediaTomato.setForeground(new java.awt.Color(255, 255, 255));
        jRLibraYMediaTomato.setText("1 1/2 Libra");

        btnTomato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vegetables_tomato_food_1814.png"))); // NOI18N
        btnTomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomatoActionPerformed(evt);
            }
        });

        jDesktopPane4.setLayer(jRMediaLibraTomato, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jRUnaLibraTomato, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jRLibraYMediaTomato, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(btnTomato, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRMediaLibraTomato)
                    .addComponent(jRUnaLibraTomato)
                    .addComponent(jRLibraYMediaTomato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTomato, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTomato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane4Layout.createSequentialGroup()
                        .addComponent(jRMediaLibraTomato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRUnaLibraTomato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRLibraYMediaTomato)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jDesktopPane6.setBackground(new java.awt.Color(204, 204, 204));

        btnWatermelon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/watermelon_96821.png"))); // NOI18N
        btnWatermelon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWatermelonActionPerformed(evt);
            }
        });

        jDesktopPane6.setLayer(btnWatermelon, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnWatermelon, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnWatermelon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnNuevaTransaccion.setBackground(new java.awt.Color(0, 255, 102));
        btnNuevaTransaccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNuevaTransaccion.setForeground(new java.awt.Color(153, 0, 0));
        btnNuevaTransaccion.setText("Nuevo Ingreso");
        btnNuevaTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaTransaccionActionPerformed(evt);
            }
        });

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla1);

        btnTotalPagar.setText("Calcular Total");
        btnTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalPagarActionPerformed(evt);
            }
        });

        jLabel1.setText("NIT:");

        jLabel6.setText("Nombre:");

        jLabel7.setText("No. Tarjeta:");

        buttonGroupTipoPago.add(jREfectivo);
        jREfectivo.setText("Efectivo");
        jREfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jREfectivoActionPerformed(evt);
            }
        });

        buttonGroupTipoPago.add(jRTarjeta);
        jRTarjeta.setText("Tarjeta");
        jRTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTarjetaActionPerformed(evt);
            }
        });

        buttonGroupTipoPago.add(jRCheque);
        jRCheque.setText("Cheque");
        jRCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRChequeActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo de Pago:");

        jLabel9.setText("No. Cheque: ");

        btnRealizarPago.setText("Realizar Pago");
        btnRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPagoActionPerformed(evt);
            }
        });

        btnSalirVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        btnSalirVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCajaLayout = new javax.swing.GroupLayout(jPanelCaja);
        jPanelCaja.setLayout(jPanelCajaLayout);
        jPanelCajaLayout.setHorizontalGroup(
            jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCajaLayout.createSequentialGroup()
                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCajaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDesktopPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDesktopPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDesktopPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCajaLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnNuevaTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCajaLayout.createSequentialGroup()
                        .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(btnTotalPagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalPagar))
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCajaLayout.createSequentialGroup()
                                        .addComponent(jREfectivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRTarjeta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRCheque))
                                    .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanelCajaLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelCajaLayout.createSequentialGroup()
                                            .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel9))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNoTarjeta)
                                                .addComponent(txtNoCheque)))
                                        .addComponent(btnRealizarPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalirVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanelCajaLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        jPanelCajaLayout.setVerticalGroup(
            jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCajaLayout.createSequentialGroup()
                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCajaLayout.createSequentialGroup()
                        .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jDesktopPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCajaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCajaLayout.createSequentialGroup()
                                        .addComponent(btnSalirVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDesktopPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))))
                    .addGroup(jPanelCajaLayout.createSequentialGroup()
                        .addContainerGap(119, Short.MAX_VALUE)
                        .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addComponent(btnNuevaTransaccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCajaLayout.createSequentialGroup()
                                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTotalPagar))
                                .addGap(71, 71, 71)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDesktopPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCajaLayout.createSequentialGroup()
                        .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jREfectivo)
                            .addComponent(jRTarjeta)
                            .addComponent(jRCheque))
                        .addGap(15, 15, 15)
                        .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRealizarPago)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        jTabbedPanePrincipal.addTab("Venta", jPanelCaja);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Caja");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Banco");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Efectos a cobrar");

        TablaEfectivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaEfectivo);

        TablaTarjeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TablaTarjeta);

        TablaCheque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(TablaCheque);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 204));
        jLabel10.setText("Asiento de Cobros");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Subtotal");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("Subtotal");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("Subtotal");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 0));
        jLabel14.setText("Total");

        btnCorteCaja.setBackground(new java.awt.Color(255, 102, 102));
        btnCorteCaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCorteCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnCorteCaja.setText("Realizar Corte");
        btnCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteCajaActionPerformed(evt);
            }
        });

        btnSalirCorteCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        btnSalirCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirCorteCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultarLayout = new javax.swing.GroupLayout(jPanelConsultar);
        jPanelConsultar.setLayout(jPanelConsultarLayout);
        jPanelConsultarLayout.setHorizontalGroup(
            jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(131, 131, 131))
                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotalCorteCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(jPanelConsultarLayout.createSequentialGroup()
                                .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSubCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel4)
                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                        .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(btnCorteCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsultarLayout.createSequentialGroup()
                                .addGap(330, 330, 330)
                                .addComponent(btnSalirCorteCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelConsultarLayout.createSequentialGroup()
                                .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtSubEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsultarLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel13))
                            .addGroup(jPanelConsultarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSubCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanelConsultarLayout.setVerticalGroup(
            jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                        .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnCorteCaja))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(btnSalirCorteCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                        .addComponent(txtTotalCorteCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );

        jTabbedPanePrincipal.addTab("Corte Caja ", jPanelConsultar);

        TablaCorriente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(TablaCorriente);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 204));
        jLabel17.setText("Cuenta corriente");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Motrar Todos");

        jRadioButton1.setText("Fecha Creación");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Nit");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Criterio de busqueda:");

        jLabel16.setText("Ingrese");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(362, 362, 362))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPanePrincipal.addTab("Cuenta Corriente", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppleActionPerformed
        // TODO add your handling code here:
        double precio=0;
        String tipo ="";
        if(!jRMediaLibraApple.isSelected()&&!jRUnaLibraApple.isSelected()&&!jRLibraYMediaApple.isSelected()){
            JOptionPane.showMessageDialog(null, "Elija una opcion");
        }else{
            //System.out.println("proceda");
            precio = getApplePrice();
            tipo = getAppleType(precio);
            p = new Productos(tipo,precio);
            rp.agregarProductos(p);
        }
        LlenarTabla();   
    }//GEN-LAST:event_btnAppleActionPerformed

    private void btnLemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLemonActionPerformed
        // TODO add your handling code here:
        double precio=0;
        String tipo ="";
        if(!jRMediaLibraLemon.isSelected()&&!jRUnaLibraLemon.isSelected()&&!jRLibraYMediaLemon.isSelected()){
            JOptionPane.showMessageDialog(null, "Elija una opcion");
        }else{
            precio = getLemonPrice();
            tipo = getLemonType(precio);
            p = new Productos(tipo,precio);
            rp.agregarProductos(p);
        }
        LlenarTabla(); 
    }//GEN-LAST:event_btnLemonActionPerformed

    private void btnPineappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPineappleActionPerformed
        // TODO add your handling code here:
        double precio=8.00;
        String tipo ="1 Piña";
        
        p = new Productos(tipo,precio);
        rp.agregarProductos(p);
        
        LlenarTabla(); 
    }//GEN-LAST:event_btnPineappleActionPerformed

    private void btnCabbageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabbageActionPerformed
        // TODO add your handling code here:
        double precio=4.20;
        String tipo ="1 Lechuga";
        
        p = new Productos(tipo,precio);
        rp.agregarProductos(p);
        
        LlenarTabla();
    }//GEN-LAST:event_btnCabbageActionPerformed

    private void btnTomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomatoActionPerformed
        // TODO add your handling code here:
        double precio=0;
        String tipo ="";
        if(!jRMediaLibraTomato.isSelected()&&!jRUnaLibraTomato.isSelected()&&!jRLibraYMediaTomato.isSelected()){
            JOptionPane.showMessageDialog(null, "Elija una opcion");
        }else{
            //System.out.println("proceda");
            precio = getTomatoPrice();
            tipo = getTomatoType(precio);
            p = new Productos(tipo,precio);
            rp.agregarProductos(p);
        }
        LlenarTabla();  
    }//GEN-LAST:event_btnTomatoActionPerformed

    private void btnWatermelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWatermelonActionPerformed
        // TODO add your handling code here:
        double precio=13.50;
        String tipo ="1 Sandía";
        
        p = new Productos(tipo,precio);
        rp.agregarProductos(p);
        
        LlenarTabla();
    }//GEN-LAST:event_btnWatermelonActionPerformed

    private void btnNuevaTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaTransaccionActionPerformed
        // TODO add your handling code here:
        habilitarBotonesNuevaTransaccion();
        rp = new RegistroProductos();
    }//GEN-LAST:event_btnNuevaTransaccionActionPerformed

    private void btnTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalPagarActionPerformed
        // TODO add your handling code here:
        habilitarBotonesCalculoPago();
        DecimalFormat df = new DecimalFormat("#.00");
        total = rp.subtotalProductos();
        String TotalTexto = String.valueOf(total);
        rp.mostrarArregloProductos();
        txtTotalPagar.setText("Q. "+TotalTexto);
    }//GEN-LAST:event_btnTotalPagarActionPerformed

    private void btnSalirVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirVentasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu mostrarMenu = new Menu();
        mostrarMenu  .setVisible(true);
        mostrarMenu  .pack();
    }//GEN-LAST:event_btnSalirVentasActionPerformed

    private void btnRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPagoActionPerformed
        // TODO add your handling code here:
        int random1=0;
        int random2=0;
        int random3=0;
        deshabilitarBotones();
        //Aqui va el codigo
        if(jREfectivo.isSelected()){
            random1 = generaNumeroAleatorio(1001,2000);
            NIT = txtNit.getText();
            Name = txtNombre.getText();
            Amount = total;
            ce = new CuentaEfectivo(NIT,Name,Amount,random1);
            re.agregarArregloEfectivo(ce);
            re.mostrarArregloEfectivo();
        }else if(jRTarjeta.isSelected()){
            random2 = generaNumeroAleatorio(2001,3000);
            NIT = txtNit.getText();
            Name = txtNombre.getText();
            Amount = total;
            Tarjeta = txtNoTarjeta.getText();
            cc = new CuentaCredito(NIT,Name,Amount,random2,Tarjeta);
            rc.agregarArregloCC(cc);
            rc.mostrarArregloCC();
            
            
            //Agrega cuenta corriente
            
            NIT = txtNit.getText();
            Name = txtNombre.getText();
            Amount = total;
            Tarjeta = txtNoTarjeta.getText();
            c = new CuentaCredito(NIT,Name,Amount,random2,Tarjeta, new Date().toString(), "", Amount, 0);
            rc.agregarCuentaCorriente(c);
            
            
            
            
            
        }else{
            random3 = generaNumeroAleatorio(3001,4000);
            NIT = txtNit.getText();
            Name = txtNombre.getText();
            Amount = total;
            Cheque = txtNoCheque.getText();
            cch = new CuentaCheque(NIT,Name,Amount,random3,Cheque);
            rch.agregarArregloCheques(cch);
            rch.mostrarArregloCheques();
        }
        //
        deshabilitarBotonesRealizarPago();
        modeloListaCol.setRowCount(0);
    }//GEN-LAST:event_btnRealizarPagoActionPerformed

    private void jREfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jREfectivoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Ya puede registrar el pago directamente!");
    }//GEN-LAST:event_jREfectivoActionPerformed

    private void jRTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTarjetaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "No olvide ingresar el número\nde la tarjeta de crédito\npara registrar el pago!");
    }//GEN-LAST:event_jRTarjetaActionPerformed

    private void jRChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRChequeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "No olvide ingresar\nel número del cheque\npara registrar el pago!");
    }//GEN-LAST:event_jRChequeActionPerformed

    private void btnCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteCajaActionPerformed
        // TODO add your handling code here:
        LlenarTablaEfectivo();
        getSubListadoEfectivo();
        LlenarTablaCredito();
        getSubListadoCredito();
        LlenarTablaCheque();
        getSubListadoCheque();
        getTotalListados();
    }//GEN-LAST:event_btnCorteCajaActionPerformed

    private void btnSalirCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirCorteCajaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu mostrarMenu = new Menu();
        mostrarMenu  .setVisible(true);
        mostrarMenu  .pack();
    }//GEN-LAST:event_btnSalirCorteCajaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    //Boton de consultar 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        LlenarTablaCorriente();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void getSubListadoEfectivo(){
        subEfectivo = re.subtotalEfectivo();
        String TotalTexto = String.valueOf(subEfectivo);
        txtSubEfectivo.setText("Q. "+TotalTexto);
    }
    
    private void getSubListadoCredito(){
        subCredito = rc.subtotalCredito();
        String TotalTexto = String.valueOf(subCredito);
        txtSubCredito.setText("Q. "+TotalTexto);
    }
    
    private void getSubListadoCheque(){
        subCheque = rch.subtotalCheques();
        String TotalTexto = String.valueOf(subCheque);
        txtSubCheque.setText("Q. "+TotalTexto);
    }
    
    private void getTotalListados(){
        TotalListados = subEfectivo+subCredito+subCheque;
        String TotalTexto1 = String.valueOf(TotalListados);
        txtTotalCorteCaja.setText("Q. "+TotalTexto1);
    }
    
    private double getLemonPrice(){
        double price=0;
        if(jRMediaLibraLemon.isSelected()){
            price = 6.25;
        }else if(jRUnaLibraLemon.isSelected()){
            price = 9.90;
        }else{
            price = 11.00;
        }
        return price;
    }
    
    private double getApplePrice(){
        double price=0;
        if(jRMediaLibraApple.isSelected()){
            price = 5.25;
        }else if(jRUnaLibraApple.isSelected()){
            price = 7.50;
        }else{
            price = 10.00;
        }
        return price;
    }
    
    private double getTomatoPrice(){
        double price=0;
        if(jRMediaLibraTomato.isSelected()){
            price = 7.40;
        }else if(jRUnaLibraTomato.isSelected()){
            price = 12.00;
        }else{
            price = 15.75;
        }
        return price;
    }
    
    private String getTomatoType(double precio){
       String type=""; 
       if(precio==7.40){
                type = "1/2 Libra Tomate";
            }else if(precio==12.00){
                type = "1 Libra Tomate";
            }else{
                type = "1 1/2 Libra Tomate";
            } 
        return type;
    }
    
    private String getAppleType(double precio){
       String type=""; 
       if(precio==5.25){
                type = "1/2 Libra Manzana";
            }else if(precio==7.50){
                type = "1 Libra Manzana";
            }else{
                type = "1 1/2 Libra Manzana";
            } 
        return type;
    }
    
    private String getLemonType(double precio){
       String type=""; 
       if(precio==6.25){
                type = "1/2 Libra Limon";
            }else if(precio==9.90){
                type = "1 Libra Limon";
            }else{
                type = "1 1/2 Libra Limon";
            } 
        return type;
    }
    
    private void LlenarTabla(){
        modeloListaCol = new DefaultTableModel();
        ArrayList<Object> listaColumnas = new ArrayList<>();
        
        listaColumnas.add("Producto");
        listaColumnas.add("Precio");
        
        for(Object o: listaColumnas){
            modeloListaCol.addColumn(o);
        }
        this.Tabla1.setModel(modeloListaCol);
        
        for (int i = 0; i < rp.arregloProductos.size(); i++) {
            modeloListaCol.addRow(new Object[]{rp.arregloProductos.get(i).getDescripcion(),rp.arregloProductos.get(i).getCosto()});
        }
        this.Tabla1.setModel(modeloListaCol);
    }
    
    private void LlenarTablaEfectivo(){
        modeloEfectivo = new DefaultTableModel();
        ArrayList<Object> listaColumnas = new ArrayList<>();
        
        listaColumnas.add("Transaccion");
        listaColumnas.add("Nit");
        listaColumnas.add("Nombre");
        listaColumnas.add("Pago");
        
        for(Object o: listaColumnas){
            modeloEfectivo.addColumn(o);
        }
        this.TablaEfectivo.setModel(modeloEfectivo);
        
        for (int i = 0; i < re.arregloEfectivo.size(); i++) {
            modeloEfectivo.addRow(new Object[]{re.arregloEfectivo.get(i).getTransaccion(),re.arregloEfectivo.get(i).getNit(),re.arregloEfectivo.get(i).getNombre(),re.arregloEfectivo.get(i).getPago()});
        }
        this.TablaEfectivo.setModel(modeloEfectivo);
    }
    
    
    private void LlenarTablaCredito(){
        modeloCredito = new DefaultTableModel();
        ArrayList<Object> listaColumnas = new ArrayList<>();
        
        listaColumnas.add("Transaccion");
        listaColumnas.add("Nit");
        listaColumnas.add("Nombre");
        listaColumnas.add("No.Tarjeta");
        listaColumnas.add("Pago");
        
        for(Object o: listaColumnas){
            modeloCredito.addColumn(o);
        }
        this.TablaTarjeta.setModel(modeloCredito);
        
        for (int i = 0; i < rc.arregloCC.size(); i++) {
            modeloCredito.addRow(new Object[]{rc.arregloCC.get(i).getCodigo(),rc.arregloCC.get(i).getNit(),rc.arregloCC.get(i).getNombre(),rc.arregloCC.get(i).getTarjeta(),rc.arregloCC.get(i).getPago()});
        }
        this.TablaTarjeta.setModel(modeloCredito);
    }
    
    //Se creo para llenado de cuenta corriente
    private void LlenarTablaCorriente(){
        modeloCuentaCorriente = new DefaultTableModel();
        
        ArrayList<Object> listaColumnas = new ArrayList<>();
        

        listaColumnas.add("Nit");
        listaColumnas.add("Nombre");
        listaColumnas.add("Fecha.Creacion");
        listaColumnas.add("Fecha.Ajuste");
        listaColumnas.add("Debe");
        listaColumnas.add("Haber");
        listaColumnas.add("Saldo");
        
        for(Object o: listaColumnas){
            modeloCuentaCorriente.addColumn(o);
           
        }
        this.TablaCorriente.setModel(modeloCuentaCorriente);
        
        for (int i = 0; i < rc.arregloCorriente.size(); i++) {
            modeloCuentaCorriente.addRow(new Object[]{
                    rc.arregloCorriente.get(i).getNit(), rc.arregloCorriente.get(i).getNombre(), 
                    rc.arregloCorriente.get(i).getFcreacionFactura(), rc.arregloCorriente.get(i).getFajusteFactura(),
                    rc.arregloCorriente.get(i).getDebe(), rc.arregloCorriente.get(i).getHaber(), rc.arregloCorriente.get(i).getDebe() - rc.arregloCorriente.get(i).getPago()});
        }
        this.TablaCorriente.setModel(modeloCuentaCorriente);
    }
    
    
    //**********************************************************************************
      private void LlenarTablaCheque(){
        modeloCheque = new DefaultTableModel();
        ArrayList<Object> listaColumnas = new ArrayList<>();
        
        listaColumnas.add("Transaccion");
        listaColumnas.add("Nit");
        listaColumnas.add("Nombre");
        listaColumnas.add("No.Cheque");
        listaColumnas.add("Pago");
        
        for(Object o: listaColumnas){
            modeloCheque.addColumn(o);
        }
        this.TablaCheque.setModel(modeloCheque);
        
        for (int i = 0; i < rch.arregloCheques.size(); i++) {
            modeloCheque.addRow(new Object[]{rch.arregloCheques.get(i).getTransaccion(),rch.arregloCheques.get(i).getNit(),rch.arregloCheques.get(i).getNombre(),rch.arregloCheques.get(i).getNumCheque(),rch.arregloCheques.get(i).getPago()});
        }
        this.TablaCheque.setModel(modeloCheque);
    }
      
      //**********************************************************************************
    private void habilitarBotonesNuevaTransaccion(){
        btnApple.setEnabled(true);
        btnLemon.setEnabled(true);
        btnTomato.setEnabled(true);
        btnPineapple.setEnabled(true);
        btnCabbage.setEnabled(true);
        btnWatermelon.setEnabled(true);
        btnTotalPagar.setEnabled(true);
        txtTotalPagar.setEnabled(true);
    }
    
    private void deshabilitarBotones(){
        btnApple.setEnabled(false);
        btnLemon.setEnabled(false);
        btnTomato.setEnabled(false);
        btnPineapple.setEnabled(false);
        btnCabbage.setEnabled(false);
        btnWatermelon.setEnabled(false);
        btnTotalPagar.setEnabled(false);
        txtTotalPagar.setEnabled(false);
        txtNit.setEnabled(false);
        txtNombre.setEnabled(false);
        jREfectivo.setEnabled(false);
        jRTarjeta.setEnabled(false);
        jRCheque.setEnabled(false);
        txtNoTarjeta.setEnabled(false);
        txtNoCheque.setEnabled(false);
        btnRealizarPago.setEnabled(false);
    }
    
    private void habilitarBotonesCalculoPago(){
        txtNit.setEnabled(true);
        txtNombre.setEnabled(true);
        jREfectivo.setEnabled(true);
        jRTarjeta.setEnabled(true);
        jRCheque.setEnabled(true);
        txtNoTarjeta.setEnabled(true);
        txtNoCheque.setEnabled(true);
        btnRealizarPago.setEnabled(true);
    }
    
    private void deshabilitarBotonesRealizarPago(){
        buttonGroupApple.clearSelection();
        buttonGroupLemon.clearSelection();
        buttonGroupTomato.clearSelection();
        txtTotalPagar.setText("");
        txtNit.setText("");
        txtNombre.setText("");
        buttonGroupTipoPago.clearSelection();
        txtNoTarjeta.setText("");
        txtNoCheque.setText("");
    }
    
    private int generaNumeroAleatorio(int min,int max){
        int numero = ThreadLocalRandom.current().nextInt(min, max + 1);
        return numero;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tiendita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tiendita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tiendita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tiendita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tiendita().setVisible(true);
            }
        });
    }
    
    public static void login(){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JTable TablaCheque;
    private javax.swing.JTable TablaCorriente;
    private javax.swing.JTable TablaEfectivo;
    private javax.swing.JTable TablaTarjeta;
    private javax.swing.JButton btnApple;
    private javax.swing.JButton btnCabbage;
    private javax.swing.JButton btnCorteCaja;
    private javax.swing.JButton btnLemon;
    private javax.swing.JButton btnNuevaTransaccion;
    private javax.swing.JButton btnPineapple;
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.JButton btnSalirCorteCaja;
    private javax.swing.JButton btnSalirVentas;
    private javax.swing.JButton btnTomato;
    private javax.swing.JButton btnTotalPagar;
    private javax.swing.JButton btnWatermelon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupApple;
    private javax.swing.ButtonGroup buttonGroupLemon;
    private javax.swing.ButtonGroup buttonGroupTipoPago;
    private javax.swing.ButtonGroup buttonGroupTomato;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JDesktopPane jDesktopPane9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCaja;
    private javax.swing.JPanel jPanelConsultar;
    private javax.swing.JRadioButton jRCheque;
    private javax.swing.JRadioButton jREfectivo;
    private javax.swing.JRadioButton jRLibraYMediaApple;
    private javax.swing.JRadioButton jRLibraYMediaLemon;
    private javax.swing.JRadioButton jRLibraYMediaTomato;
    private javax.swing.JRadioButton jRMediaLibraApple;
    private javax.swing.JRadioButton jRMediaLibraLemon;
    private javax.swing.JRadioButton jRMediaLibraTomato;
    private javax.swing.JRadioButton jRTarjeta;
    private javax.swing.JRadioButton jRUnaLibraApple;
    private javax.swing.JRadioButton jRUnaLibraLemon;
    private javax.swing.JRadioButton jRUnaLibraTomato;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNoCheque;
    private javax.swing.JTextField txtNoTarjeta;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSubCheque;
    private javax.swing.JTextField txtSubCredito;
    private javax.swing.JTextField txtSubEfectivo;
    private javax.swing.JTextField txtTotalCorteCaja;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
